### ISSUE TITLE
[Android] Borders and shadows not rendering properly

### ISSUE THREAD

**Issue by SpaghettiC0des** [osaisacson/kretsloppan#6]

**Comment by osaisacson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Android] general first review and fix of found minor bugs. Add major bugs as separate cards (1)](https://trello.com/c/l30AJYlG/22-android-general-first-review-and-fix-of-found-minor-bugs-add-major-bugs-as-separate-cards-1)
